const data = [
  {
    "Song name": "viva la vida",
    Artist: "corandcrank",
    Genre: "Dance/Electronic",
    Region: "Azerbaijan",
    "Release year": 2019,
    Tempo: 86,
    Key: "C",
    "Lyrics(Speachyness)": 1.05,
    Cover: 1,
    AverageColor: "#bfbfbf",
  },
  {
    "Song name": "Woman",
    Artist: "little sims",
    Genre: "British hip hop",
    Region: "England",
    "Release year": 2021,
    Tempo: 87,
    Key: "C#",
    "Lyrics(Speachyness)": 2.09,
    Cover: 2,
    AverageColor: "#885405",
  },
  {
    "Song name": "EARFQUAKE",
    Artist: "Tyler, The Creator",
    Genre: "Hip-Hop/Rap",
    Region: "American",
    "Release year": 2019,
    Tempo: 80,
    Key: "A",
    "Lyrics(Speachyness)": 0.685,
    Cover: 3,
    AverageColor: "#a17e88",
  },
  {
    "Song name": "From the sun",
    Artist: "Unknown Mortal Orchestra",
    Genre: "Alternative/Indie, Rock",
    Region: "New Zealand",
    "Release year": 2013,
    Tempo: 84,
    Key: "F#",
    "Lyrics(Speachyness)": 0.586,
    Cover: 4,
    AverageColor: "#935f51",
  },
  {
    "Song name": "Dastaan",
    Artist: "Tajdar Junaid",
    Genre: "Pop",
    Region: "India",
    "Release year": 2013,
    Tempo: 160,
    Key: "A",
    "Lyrics(Speachyness)": 0.721,
    Cover: 5,
    AverageColor: "#917b74",
  },
  {
    "Song name": "Ich geh heut nicht mehr tanzen",
    Artist: "annenmaykantereit",
    Genre: "Rock",
    Region: "Germany",
    "Release year": 2018,
    Tempo: 121,
    Key: "F",
    "Lyrics(Speachyness)": 0.401,
    Cover: 6,
    AverageColor: "#c3ad9f",
  },
  {
    "Song name": "Los libros de la buena memoria",
    Artist: "Invisible",
    Genre: "Spanish Rock",
    Region: "Spain",
    "Release year": 1976,
    Tempo: 169,
    Key: "E",
    "Lyrics(Speachyness)": 0.453,
    Cover: 7,
    AverageColor: "#7e757b",
  },
  {
    "Song name": "Иуда",
    Artist: "Husky",
    Genre: "Hip-Hop/Rap",
    Region: "Russia",
    "Release year": 2018,
    Tempo: 108,
    Key: "A#",
    "Lyrics(Speachyness)": 3.18,
    Cover: 8,
    AverageColor: "#b9b9b9",
  },
  {
    "Song name": "at the movies on quaaludes",
    Artist: "The Flaming Lips",
    Genre: "Alternative/Indie",
    Region: "American",
    "Release year": 2020,
    Tempo: 78,
    Key: "G",
    "Lyrics(Speachyness)": 0.393,
    Cover: 9,
    AverageColor: "#a58e88",
  },
  {
    "Song name": "pink diamond",
    Artist: "Charli XCX",
    Genre: "Pop",
    Region: "American",
    "Release year": 2020,
    Tempo: 141,
    Key: "B#",
    "Lyrics(Speachyness)": 3.34,
    Cover: 10,
    AverageColor: "#b4a7a8",
  },
  {
    "Song name": "Everybody ciao",
    Artist: "Daniele Benati",
    Genre: "Pop",
    Region: "Italy",
    "Release year": 2014,
    Tempo: 129,
    Key: "G",
    "Lyrics(Speachyness)": 0.445,
    Cover: 11,
    AverageColor: "#727076",
  },
  {
    "Song name": "Eux",
    Artist: "Dalida",
    Genre: "Pop music, Rock and roll",
    Region: "France",
    "Release year": 1963,
    Tempo: 68,
    Key: "F#",
    "Lyrics(Speachyness)": 0.357,
    Cover: 12,
    AverageColor: "#ac6541",
  },
  {
    "Song name": "Start me up",
    Artist: "The rolling stones",
    Genre: "Blues",
    Region: "England",
    "Release year": 2009,
    Tempo: 123,
    Key: "F",
    "Lyrics(Speachyness)": 0.354,
    Cover: 13,
    AverageColor: "#83414c",
  },
  {
    "Song name": "When you die",
    Artist: "MGMT",
    Genre: "Alternative/Indie",
    Region: "American",
    "Release year": 2018,
    Tempo: 141,
    Key: "B",
    "Lyrics(Speachyness)": 0.391,
    Cover: 14,
    AverageColor: "#d4bb48",
  },
  {
    "Song name": "AMERIKA",
    Artist: "Rammstein",
    Genre: "Industrial metal",
    Region: "Germany",
    "Release year": 2004,
    Tempo: 126,
    Key: "D",
    "Lyrics(Speachyness)": 0.963,
    Cover: 15,
    AverageColor: "#e08d66",
  },
  {
    "Song name": "I Hear The Day come",
    Artist: "Matt Maltese",
    Genre: "Singer-Songwriter",
    Region: "England",
    "Release year": 2016,
    Tempo: 127,
    Key: "C",
    "Lyrics(Speachyness)": 0.319,
    Cover: 16,
    AverageColor: "#d9d2d6",
  },
  {
    "Song name": "Milestones",
    Artist: "Shook",
    Genre: "Dance/Electronic",
    Region: "Netherlands",
    "Release year": 2014,
    Tempo: 118,
    Key: "B",
    "Lyrics(Speachyness)": 0.394,
    Cover: 17,
    AverageColor: "#575757",
  },
  {
    "Song name": "Les pions se revoltent",
    Artist: "Cissy Street",
    Genre: "Jazz",
    Region: "France",
    "Release year": 2020,
    Tempo: 108,
    Key: "c",
    "Lyrics(Speachyness)": 0.569,
    Cover: 18,
    AverageColor: "#ac8c62",
  },
  {
    "Song name": "clair de lune",
    Artist: "Kamasi Washington",
    Genre: "Jazz",
    Region: "United States",
    "Release year": 2015,
    Tempo: 132,
    Key: "c#",
    "Lyrics(Speachyness)": 0.326,
    Cover: 19,
    AverageColor: "#545454",
  },
  {
    "Song name": "sonne",
    Artist: "Rammestein",
    Genre: "Neue Deutsche Härte, Industrial metal, Meta",
    Region: "Germany",
    "Release year": 2001,
    Tempo: 76,
    Key: "E",
    "Lyrics(Speachyness)": 0.854,
    Cover: 20,
    AverageColor: "#83816f",
  },
  {
    "Song name": "let down",
    Artist: "Easy Star All-Stars,Toots & The Maytals",
    Genre: "Reggae",
    Region: "United States",
    "Release year": 2006,
    Tempo: 114,
    Key: "A",
    "Lyrics(Speachyness)": 0.394,
    Cover: 21,
    AverageColor: "#998268",
  },
  {
    "Song name": "zungguzungguguzungguzeng",
    Artist: "Yellowman",
    Genre: "Reggae",
    Region: "Jamaica",
    "Release year": 1983,
    Tempo: 165,
    Key: "F#",
    "Lyrics(Speachyness)": 2.43,
    Cover: 22,
    AverageColor: "#9d502a",
  },
  {
    "Song name": "BOB",
    Artist: "Outkast",
    Genre: "Hip Hop",
    Region: "United States of America",
    "Release year": 2000,
    Tempo: 154,
    Key: "A",
    "Lyrics(Speachyness)": 0.978,
    Cover: 23,
    AverageColor: "#817772",
  },
  {
    "Song name": "Dogs",
    Artist: "Pink Floyd",
    Genre: "Progressive Rock",
    Region: "England",
    "Release year": 1977,
    Tempo: 110,
    Key: "D",
    "Lyrics(Speachyness)": 0.5,
    Cover: 24,
    AverageColor: "#69553b",
  },
  {
    "Song name": "Epitaph",
    Artist: "King Crimson",
    Genre: "Progressive Rock",
    Region: "England",
    "Release year": 1969,
    Tempo: 130,
    Key: "E",
    "Lyrics(Speachyness)": 0.322,
    Cover: 25,
    AverageColor: "#a0737b",
  },
  {
    "Song name": "ロンググッドバイ",
    Artist: "kinokoteikoku",
    Genre: "Rock",
    Region: "Japan",
    "Release year": 2020,
    Tempo: 87,
    Key: "D",
    "Lyrics(Speachyness)": 0.516,
    Cover: 26,
    AverageColor: "#333b65",
  },
  {
    "Song name": "フェイクワールドワンダーランド",
    Artist: "kinokoteikoku",
    Genre: "Rock",
    Region: "Japan",
    "Release year": 2014,
    Tempo: 82,
    Key: "C",
    "Lyrics(Speachyness)": 0.318,
    Cover: 27,
    AverageColor: "#9bb299",
  },
  {
    "Song name": "six missed calls",
    Artist: "Elah Hale",
    Genre: "R&B",
    Region: "United States",
    "Release year": 2019,
    Tempo: 116,
    Key: "F#",
    "Lyrics(Speachyness)": 0.339,
    Cover: 28,
    AverageColor: "#a16153",
  },
  {
    "Song name": "five string serenade",
    Artist: "Mazzy Star",
    Genre: "Rock",
    Region: "United States",
    "Release year": 1993,
    Tempo: 162,
    Key: "G",
    "Lyrics(Speachyness)": 0.318,
    Cover: 29,
    AverageColor: "#764966",
  },
  {
    "Song name": "girl with basket of fruit",
    Artist: "Xiu Xiu",
    Genre: "Experimetal, Indie Rock, Art Rock",
    Region: "United States",
    "Release year": 2019,
    Tempo: 130,
    Key: "A#",
    "Lyrics(Speachyness)": 1.86,
    Cover: 30,
    AverageColor: "#470981",
  },
  {
    "Song name": "full moon in gemini",
    Artist: "Vagabon",
    Genre: "Alternative/Indie, New Wave",
    Region: "Unites States",
    "Release year": 2019,
    Tempo: 157,
    Key: "D",
    "Lyrics(Speachyness)": 0.317,
    Cover: 31,
    AverageColor: "#a25539",
  },
  {
    "Song name": "strange encounter",
    Artist: "Father John Misty",
    Genre: "Indie folk; indie rock; soft rock;",
    Region: "United States",
    "Release year": 2015,
    Tempo: 184,
    Key: "D",
    "Lyrics(Speachyness)": 0.591,
    Cover: 32,
    AverageColor: "#ad9283",
  },
  {
    "Song name": "another weekend",
    Artist: "Ariel Pink",
    Genre: "Rock",
    Region: "United States",
    "Release year": 2017,
    Tempo: 109,
    Key: "F#",
    "Lyrics(Speachyness)": 0.278,
    Cover: 33,
    AverageColor: "#5c4f58",
  },
  {
    "Song name": "lo boob oscillator",
    Artist: "Stereolab",
    Genre: "Indie rock, Post-rock, Jazz",
    Region: "United Kingdom",
    "Release year": 1995,
    Tempo: 124,
    Key: "E",
    "Lyrics(Speachyness)": 0.449,
    Cover: 34,
    AverageColor: "#b97646",
  },
  {
    "Song name": "planet caravan",
    Artist: "Black Sabbath",
    Genre: "Heavy metal, Hard rock, Doom metal",
    Region: "United Kingdom",
    "Release year": 1970,
    Tempo: 91,
    Key: "D",
    "Lyrics(Speachyness)": 0.366,
    Cover: 35,
    AverageColor: "#361c23",
  },
  {
    "Song name": "fuwarin",
    Artist: "Ichiko Aoba",
    Genre: "Alternative/ Indie",
    Region: "Japan",
    "Release year": 2010,
    Tempo: 85,
    Key: "C",
    "Lyrics(Speachyness)": 0.382,
    Cover: 36,
    AverageColor: "#ffffff",
  },
  {
    "Song name": "powerful",
    Artist: "Earth Dad, Ruru",
    Genre: "Space age pop, Pop",
    Region: "United States",
    "Release year": 2019,
    Tempo: 128,
    Key: "B",
    "Lyrics(Speachyness)": 0.322,
    Cover: 37,
    AverageColor: "#96905f",
  },
  {
    "Song name": "borders",
    Artist: "M.I.A.",
    Genre: "Dance/Electronica",
    Region: "United Kingdom",
    "Release year": 2016,
    Tempo: 179,
    Key: "C#",
    "Lyrics(Speachyness)": 0.864,
    Cover: 38,
    AverageColor: "#cb5e35",
  },
  {
    "Song name": "morning sun",
    Artist: "Al Barry",
    Genre: "Reggae",
    Region: "United States of America",
    "Release year": 2002,
    Tempo: 114,
    Key: "A",
    "Lyrics(Speachyness)": 0.756,
    Cover: 39,
    AverageColor: "#716270",
  },
  {
    "Song name": "the golden age",
    Artist: "Beck",
    Genre: "Folk Rock",
    Region: "United States of America",
    "Release year": 2002,
    Tempo: 125,
    Key: "F#",
    "Lyrics(Speachyness)": 0.333,
    Cover: 40,
    AverageColor: "#a48c8f",
  },
  {
    "Song name": "laika",
    Artist: "Sticky Fingers",
    Genre: "Alternative/ Indie",
    Region: "Australia",
    "Release year": 2013,
    Tempo: 144,
    Key: "F#",
    "Lyrics(Speachyness)": 0.365,
    Cover: 41,
    AverageColor: "#857366",
  },
  {
    "Song name": "chondramalacia patella",
    Artist: "Black midi",
    Genre: "Prog Rock",
    Region: "England",
    "Release year": 2021,
    Tempo: 86,
    Key: "C#",
    "Lyrics(Speachyness)": 0.964,
    Cover: 42,
    AverageColor: "#48444d",
  },
  {
    "Song name": "stairway to heaven",
    Artist: "Led Zeppelin",
    Genre: "Rock, Blues",
    Region: "England",
    "Release year": 1971,
    Tempo: 83,
    Key: "A",
    "Lyrics(Speachyness)": 0.339,
    Cover: 43,
    AverageColor: "#9d968f",
  },
  {
    "Song name": "jigsaw falling into place",
    Artist: "Radiohead",
    Genre: "Rock",
    Region: "England",
    "Release year": 2007,
    Tempo: 166,
    Key: "",
    "Lyrics(Speachyness)": 0.479,
    Cover: 44,
    AverageColor: "#6d4b32",
  },
  {
    "Song name": "wanna be startin something",
    Artist: "Micheal Jackson",
    Genre: "Pop",
    Region: "United States of America",
    "Release year": 1982,
    Tempo: 123,
    Key: "A",
    "Lyrics(Speachyness)": 0.455,
    Cover: 45,
    AverageColor: "#8e8789",
  },
  {
    "Song name": "whats your pleasure?",
    Artist: "Jessie Ware",
    Genre: "Disco/ Pop",
    Region: "England",
    "Release year": 2020,
    Tempo: 116,
    Key: "",
    "Lyrics(Speachyness)": 0.392,
    Cover: 46,
    AverageColor: "#8f7f74",
  },
  {
    "Song name": "Rush, Rush",
    Artist: "Debbie Harry",
    Genre: "Post Disco",
    Region: "United States of America",
    "Release year": 1983,
    Tempo: 131,
    Key: "C",
    "Lyrics(Speachyness)": 0.555,
    Cover: 47,
    AverageColor: "#e2b194",
  },
  {
    "Song name": "Treading lightly",
    Artist: "Fazerdaze",
    Genre: "Alternative/ Indie",
    Region: "New Zealand",
    "Release year": 2014,
    Tempo: 140,
    Key: "C#",
    "Lyrics(Speachyness)": 0.29,
    Cover: 48,
    AverageColor: "#954c45",
  },
  {
    "Song name": "N.E.O",
    Artist: "CHAI",
    Genre: "Alternative/ Indie, Pop",
    Region: "Japan",
    "Release year": 2017,
    Tempo: 134,
    Key: "F#",
    "Lyrics(Speachyness)": 0.385,
    Cover: 49,
    AverageColor: "#e51e83",
  },
  {
    "Song name": "Alive",
    Artist: "Ravyn Lenae",
    Genre: "R&B, Soul",
    Region: "United States of America",
    "Release year": 2016,
    Tempo: 172,
    Key: "A",
    "Lyrics(Speachyness)": 2.79,
    Cover: 50,
    AverageColor: "#482876",
  },
  {
    "Song name": "Video Killed The Radio Star",
    Artist: "The Buggles",
    Genre: "Pop",
    Region: "England",
    "Release year": 1980,
    Tempo: 132,
    Key: "C#",
    "Lyrics(Speachyness)": 0.754,
    Cover: 51,
    AverageColor: "#c3b5a7",
  },
  {
    "Song name": "Tezeta",
    Artist: "Mulatu Astake",
    Genre: "Ethio-Jazz",
    Region: "Ethiopia",
    "Release year": 1998,
    Tempo: 82,
    Key: "A#",
    "Lyrics(Speachyness)": 0.416,
    Cover: 52,
    AverageColor: "#e5e0d9",
  },
  {
    "Song name": "Chan Chan",
    Artist: "Buena Vista Social Club",
    Genre: "Latin Pop",
    Region: "Cuba",
    "Release year": 1997,
    Tempo: 83,
    Key: "D",
    "Lyrics(Speachyness)": 0.341,
    Cover: 53,
    AverageColor: "#695e48",
  },
  {
    "Song name": "White sands",
    Artist: "Tommy Guerrero",
    Genre: "Alternative/ Indie",
    Region: "United States of America",
    "Release year": 2018,
    Tempo: 92,
    Key: "B#",
    "Lyrics(Speachyness)": 0.295,
    Cover: 54,
    AverageColor: "#8f804f",
  },
];

export default data;
